import Head from 'next/head'
import Link from 'next/link'
import { Button } from 'antd'
export default function Login() {
  return (
    <>
      <Head>
        <title>Naruto-Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex items-center justify-center w-screen h-screen'>
        <Link href='/home'>
          <Button>登录</Button>
        </Link>
      </main>
    </>
  )
}
