import Head from 'next/head'
export default function Home() {
  return (
    <>
      <Head>
        <title>Naruto-Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-blue w-screen h-screen'>
      </main>
    </>
  )
}
